# Generated by Django 6.1 on 2026-09-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Software System', max_length=100)),
                ('feasibility_score', models.IntegerField(default=85)),
                ('feasibility_summary', models.TextField(blank=True, default='')),
                ('feasibility_breakdown', models.JSONField(blank=True, default=dict)),
                ('tech_stack', models.JSONField(blank=True, default=dict)),
                ('dna_data', models.JSONField(blank=True, default=dict)),
                ('build_plan', models.JSONField(blank=True, default=list)),
                ('risks_mitigations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matrix.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='Core Logic', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(blank=True, default=list)),
                ('outputs', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='matrix.project')),
            ],
        ),
    ]
