# Generated by Django 6.1 on 2026-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tagline',
        ),
        migrations.AddField(
            model_name='componentnode',
            name='connected_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='componentnode',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='action_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='feasibility_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='idea_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='is_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='target_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
