"""Domain DNA templates used when no live LLM is configured."""


def ecommerce_dna(idea):
    return {
        "project_name": "Customer Storefront & Order Platform",
        "project_type": "E-Commerce Application",
        "problem": "Shoppers need a reliable path from catalog to paid, fulfillable orders.",
        "goal": "Let a customer browse products, check out, pay, and track delivery.",
        "summary": "Customer → website → backend → product database → payment → order → delivery.",
        "target_users": ["Shoppers", "Store operators", "Warehouse staff"],
        "inputs": ["Product browse", "Cart contents", "Payment details", "Shipping address"],
        "outputs": ["Order confirmation", "Payment receipt", "Packing list", "Delivery status"],
        "software": ["Django or Node API", "PostgreSQL", "Stripe", "React storefront"],
        "hardware": ["Cloud application servers"],
        "data": ["Product catalog", "Inventory counts", "Orders", "Payment tokens"],
        "ai_ml_requirements": "Optional recommendations later. Checkout itself is transactional, not ML.",
        "components": [
            {"id": "comp-customer", "name": "Customer", "category": "Input", "purpose": "Person who browses and buys.", "description": "Human actor starting the purchase.", "inputs": ["Intent to buy"], "outputs": ["Browse and checkout actions"], "technologies": ["Browser / phone"], "dependencies": [], "connected_components": ["Storefront website"]},
            {"id": "comp-web", "name": "Storefront website", "category": "Input", "purpose": "Shows catalog, cart, and checkout forms.", "description": "Web UI for the shop.", "inputs": ["Customer clicks"], "outputs": ["API requests"], "technologies": ["React"], "dependencies": [], "connected_components": ["Commerce backend"]},
            {"id": "comp-backend", "name": "Commerce backend", "category": "Processing", "purpose": "Validates cart, prices, and order state.", "description": "Application services for catalog and checkout.", "inputs": ["Cart payloads"], "outputs": ["Order records"], "technologies": ["Django"], "dependencies": ["comp-web"], "connected_components": ["Product database", "Payment service"]},
            {"id": "comp-db", "name": "Product database", "category": "Storage", "purpose": "Stores SKUs, prices, and stock.", "description": "Source of truth for catalog and inventory.", "inputs": ["Reads/writes"], "outputs": ["Product and stock rows"], "technologies": ["PostgreSQL"], "dependencies": ["comp-backend"], "connected_components": ["Commerce backend"]},
            {"id": "comp-pay", "name": "Payment service", "category": "Decision", "purpose": "Authorizes and captures funds.", "description": "External payment processor.", "inputs": ["Payable amount"], "outputs": ["Authorization result"], "technologies": ["Stripe"], "dependencies": ["comp-backend"], "connected_components": ["Order pipeline"]},
            {"id": "comp-order", "name": "Order pipeline", "category": "Processing", "purpose": "Creates the paid order and packing job.", "description": "Order state machine.", "inputs": ["Paid checkout"], "outputs": ["Fulfillment ticket"], "technologies": ["PostgreSQL", "Workers"], "dependencies": ["comp-pay"], "connected_components": ["Delivery"]},
            {"id": "comp-delivery", "name": "Delivery", "category": "Output", "purpose": "Gets the package to the customer.", "description": "Shipping / last-mile handoff.", "inputs": ["Packed order"], "outputs": ["Tracking status"], "technologies": ["Carrier API"], "dependencies": ["comp-order"], "connected_components": []},
        ],
        "dependencies": ["Stripe", "PostgreSQL"],
        "logic": "If cart has items AND stock is available AND payment authorizes, create order and start packing.",
        "workflow": "Customer -> Website -> Backend -> Product DB -> Payment -> Order -> Delivery",
        "risks": ["Payment failure", "Overselling stock", "Address errors"],
        "constraints": ["Never store raw card numbers", "Stock check before capture"],
        "feasibility": {
            "score": 86,
            "technical": "High — standard commerce pattern",
            "software": "Mature open-source plus a payment provider",
            "hardware": "Cloud hosts only",
            "data_requirements": "Product catalog and inventory must exist",
            "complexity": "Moderate",
            "assessment": "Buildable with a small team. Hard parts are payments, stock, and fulfillment — not the landing page.",
        },
        "build_steps": [
            {"step_number": 1, "title": "Catalog and inventory schema", "description": "Model products, variants, and stock counts.", "required_components": ["Product database"], "expected_result": "You can list products with real stock.", "status": "current"},
            {"step_number": 2, "title": "Storefront and cart", "description": "Browse, add to cart, persist cart server-side.", "required_components": ["Storefront website", "Commerce backend"], "expected_result": "A shopper can fill a cart.", "status": "next"},
            {"step_number": 3, "title": "Checkout and payment authorization", "description": "Create payment intents and handle success/failure webhooks.", "required_components": ["Payment service"], "expected_result": "A test card can authorize a cart.", "status": "next"},
            {"step_number": 4, "title": "Order creation after pay", "description": "Write order rows only after authorization succeeds.", "required_components": ["Order pipeline"], "expected_result": "Paid carts become orders, unpaid carts do not.", "status": "next"},
            {"step_number": 5, "title": "Fulfillment and tracking", "description": "Packing list plus a delivery status the customer can see.", "required_components": ["Delivery"], "expected_result": "An order moves from paid to shipped with a tracking id.", "status": "next"},
        ],
    }


def vision_dna(idea):
    return {
        "project_name": "Computer Vision Application",
        "project_type": "Computer Vision System",
        "problem": "Images need to be turned into usable labels or events for an application.",
        "goal": "Capture a frame, preprocess it, run a model, store the result, and show it in an app.",
        "summary": "Camera → image → preprocessing → model → prediction → database → application.",
        "target_users": ["Operators", "Application users"],
        "inputs": ["Camera frames", "Detection threshold"],
        "outputs": ["Labels or bounding boxes", "Stored events", "App notifications"],
        "software": ["Python", "OpenCV", "ONNX or PyTorch", "Django"],
        "hardware": ["Camera", "CPU or GPU host"],
        "data": ["Image frames", "Prediction records"],
        "ai_ml_requirements": "A real model is required only if you need learned detection. Until then, treat outputs as simulation.",
        "components": [
            {"id": "comp-cam", "name": "Camera", "category": "Input", "purpose": "Captures the scene as frames.", "description": "USB or IP camera.", "inputs": ["Light from scene"], "outputs": ["Raw frames"], "technologies": ["OpenCV"], "dependencies": [], "connected_components": ["Image buffer"]},
            {"id": "comp-img", "name": "Image buffer", "category": "Processing", "purpose": "Holds the latest frame for processing.", "description": "In-memory frame queue.", "inputs": ["Raw frames"], "outputs": ["Queued images"], "technologies": ["NumPy"], "dependencies": ["comp-cam"], "connected_components": ["Preprocessing"]},
            {"id": "comp-prep", "name": "Preprocessing", "category": "Processing", "purpose": "Resize, normalize, and crop the frame.", "description": "Makes the image model-ready.", "inputs": ["Queued images"], "outputs": ["Tensors / arrays"], "technologies": ["OpenCV"], "dependencies": ["comp-img"], "connected_components": ["Vision model"]},
            {"id": "comp-model", "name": "Vision model", "category": "Intelligence", "purpose": "Scores the frame for classes or objects.", "description": "Placeholder until a trained model is loaded.", "inputs": ["Preprocessed arrays"], "outputs": ["Scores"], "technologies": ["ONNX Runtime"], "dependencies": ["comp-prep"], "connected_components": ["Prediction gate"]},
            {"id": "comp-pred", "name": "Prediction gate", "category": "Decision", "purpose": "Accepts scores above a threshold.", "description": "Rule on top of model scores.", "inputs": ["Scores"], "outputs": ["Accepted labels"], "technologies": ["Python"], "dependencies": ["comp-model"], "connected_components": ["Event database"]},
            {"id": "comp-db", "name": "Event database", "category": "Storage", "purpose": "Stores accepted detections.", "description": "Queryable history.", "inputs": ["Labels"], "outputs": ["Event rows"], "technologies": ["PostgreSQL"], "dependencies": ["comp-pred"], "connected_components": ["Application"]},
            {"id": "comp-app", "name": "Application", "category": "Output", "purpose": "Shows detections to a person.", "description": "Operator UI.", "inputs": ["Event rows"], "outputs": ["On-screen results"], "technologies": ["Web UI"], "dependencies": ["comp-db"], "connected_components": []},
        ],
        "dependencies": ["OpenCV", "A camera device"],
        "logic": "If a frame is ready and score >= threshold, write an event and refresh the app.",
        "workflow": "Camera -> Image -> Preprocessing -> Model -> Prediction -> Database -> Application",
        "risks": ["Poor lighting", "No trained weights yet", "Camera disconnect"],
        "constraints": ["Do not report accuracy % without an evaluation set"],
        "feasibility": {
            "score": 78,
            "technical": "Pipeline is straightforward; accuracy depends on a real model",
            "software": "OpenCV plus an inference runtime",
            "hardware": "Camera plus a machine that can run inference",
            "data_requirements": "Labeled images if you train; otherwise simulation only",
            "complexity": "Moderate to high if you train from scratch",
            "assessment": "The plumbing is feasible now. Treat detections as simulated until weights are trained and evaluated.",
        },
        "build_steps": [
            {"step_number": 1, "title": "Get a live camera frame", "description": "Open the camera and display frames.", "required_components": ["Camera", "Image buffer"], "expected_result": "A moving image on screen.", "status": "current"},
            {"step_number": 2, "title": "Preprocess consistently", "description": "Resize and color-convert every frame the same way.", "required_components": ["Preprocessing"], "expected_result": "Fixed-size arrays leaving preprocessing.", "status": "next"},
            {"step_number": 3, "title": "Run inference or a stub", "description": "Load a model if you have one; otherwise a stub that is labeled simulation.", "required_components": ["Vision model"], "expected_result": "A score per frame with a clear source label.", "status": "next"},
            {"step_number": 4, "title": "Threshold and store", "description": "Keep only scores above threshold.", "required_components": ["Prediction gate", "Event database"], "expected_result": "Events appear in the database.", "status": "next"},
            {"step_number": 5, "title": "Application view", "description": "Show the latest detection to an operator.", "required_components": ["Application"], "expected_result": "A person can see when a detection fired.", "status": "next"},
        ],
    }


def robot_dna(idea):
    return {
        "project_name": "Sense-Plan-Act Robot",
        "project_type": "Robotics System",
        "problem": "The robot must sense its environment, decide, and move without blindly driving into obstacles.",
        "goal": "Read sensors, run a controller, drive motors, and keep a human-visible status.",
        "summary": "Environment → sensors → controller → motors / AI assist → robot motion.",
        "target_users": ["Robot operators", "Developers"],
        "inputs": ["Distance reading", "Battery level", "Target waypoint"],
        "outputs": ["Motor commands", "Pose estimate", "Stop/fault status"],
        "software": ["Python or C++", "ROS 2 optional", "Serial/GPIO"],
        "hardware": ["Robot chassis", "Distance sensors", "Motor drivers", "Onboard computer"],
        "data": ["Sensor samples", "Command logs"],
        "ai_ml_requirements": "Optional perception model. Motion here uses rule-based control unless a planner is trained.",
        "components": [
            {"id": "comp-env", "name": "Environment", "category": "Input", "purpose": "The physical space the robot moves in.", "description": "Obstacles and floor.", "inputs": ["Physics of the room"], "outputs": ["Reflected signals"], "technologies": ["Real world"], "dependencies": [], "connected_components": ["Onboard sensors"]},
            {"id": "comp-sensors", "name": "Onboard sensors", "category": "Input", "purpose": "Measure distance, bump, and battery.", "description": "Ultrasonic/lidar plus power monitor.", "inputs": ["Environment"], "outputs": ["Sensor values"], "technologies": ["GPIO / I2C"], "dependencies": ["comp-env"], "connected_components": ["Robot controller"]},
            {"id": "comp-ctrl", "name": "Robot controller", "category": "Decision", "purpose": "Turns sensor values into move/stop.", "description": "Onboard control loop.", "inputs": ["Sensor values"], "outputs": ["Motion setpoints"], "technologies": ["Microcontroller or SBC"], "dependencies": ["comp-sensors"], "connected_components": ["Motors", "Onboard AI assist"]},
            {"id": "comp-ai", "name": "Onboard AI assist", "category": "Intelligence", "purpose": "Optional extra perception or path hint.", "description": "Not required for a first driving loop.", "inputs": ["Camera or scan"], "outputs": ["Suggested heading"], "technologies": ["ONNX optional"], "dependencies": ["comp-sensors"], "connected_components": ["Robot controller"]},
            {"id": "comp-motors", "name": "Motors", "category": "Output", "purpose": "Create motion.", "description": "Wheels or joints.", "inputs": ["PWM / CAN commands"], "outputs": ["Physical movement"], "technologies": ["Motor driver"], "dependencies": ["comp-ctrl"], "connected_components": ["Robot body"]},
            {"id": "comp-body", "name": "Robot body", "category": "Output", "purpose": "The moving platform the user sees.", "description": "Chassis in the environment.", "inputs": ["Motor torque"], "outputs": ["Changed pose"], "technologies": ["Mechanical"], "dependencies": ["comp-motors"], "connected_components": []},
        ],
        "dependencies": ["Motor driver", "Distance sensor"],
        "logic": "If obstacle < 25 cm or battery < 12%, motors off. Else drive toward the waypoint.",
        "workflow": "Environment -> Sensors -> Controller -> Motors -> Robot body",
        "risks": ["Sensor blind spots", "Brownout", "Uncommanded motion"],
        "constraints": ["E-stop must cut motors independently of software"],
        "feasibility": {
            "score": 74,
            "technical": "A slow indoor rover is feasible; manipulation is harder",
            "software": "A simple control loop first, ROS later if needed",
            "hardware": "Chassis, drivers, sensors, battery, e-stop",
            "data_requirements": "Logged sensor traces help tuning; not a labeled ML set",
            "complexity": "High for hardware integration",
            "assessment": "Start with stop-on-obstacle before any learned planner.",
        },
        "build_steps": [
            {"step_number": 1, "title": "Read one distance sensor", "description": "Print live centimeters to a console.", "required_components": ["Onboard sensors"], "expected_result": "Numbers change when you put a hand in front.", "status": "current"},
            {"step_number": 2, "title": "Stop rule in the controller", "description": "If distance is below a limit, command zero speed.", "required_components": ["Robot controller"], "expected_result": "Software refuses to drive into a close object.", "status": "next"},
            {"step_number": 3, "title": "Motor drive with e-stop", "description": "Move slowly in open space; e-stop cuts power.", "required_components": ["Motors", "Robot body"], "expected_result": "The chassis moves and can be halted instantly.", "status": "next"},
            {"step_number": 4, "title": "Closed loop drive", "description": "Combine sensor + controller + motors in one loop.", "required_components": ["Robot controller", "Motors"], "expected_result": "The robot approaches a target and stops near obstacles.", "status": "next"},
            {"step_number": 5, "title": "Optional perception assist", "description": "Add camera/AI only after the safety loop is trusted.", "required_components": ["Onboard AI assist"], "expected_result": "Heading hints that never override e-stop.", "status": "next"},
        ],
    }


def analytics_dna(idea):
    return {
        "project_name": "Data Analytics Platform",
        "project_type": "Cloud / Data Platform",
        "problem": "Raw events are hard to trust, query, and chart without a pipeline.",
        "goal": "Ingest events, store them, compute metrics, and show dashboards.",
        "summary": "Event source → ingest → warehouse → metrics → dashboard, with optional anomaly rules.",
        "target_users": ["Analysts", "Operators"],
        "inputs": ["Application events", "Time range", "Metric definitions"],
        "outputs": ["Aggregated metrics", "Charts", "Optional alerts"],
        "software": ["Python", "PostgreSQL or warehouse", "A dashboard UI"],
        "hardware": ["Cloud compute and storage"],
        "data": ["Event logs", "Aggregates"],
        "ai_ml_requirements": "Anomaly scoring is optional. Default alerts are threshold rules.",
        "components": [
            {"id": "comp-src", "name": "Event sources", "category": "Input", "purpose": "Applications emitting events.", "description": "Logs or product telemetry.", "inputs": ["User/system actions"], "outputs": ["Event payloads"], "technologies": ["HTTP / queue"], "dependencies": [], "connected_components": ["Ingest API"]},
            {"id": "comp-ingest", "name": "Ingest API", "category": "Processing", "purpose": "Accepts and validates events.", "description": "Entry service.", "inputs": ["Event payloads"], "outputs": ["Clean events"], "technologies": ["Django / FastAPI"], "dependencies": ["comp-src"], "connected_components": ["Event warehouse"]},
            {"id": "comp-wh", "name": "Event warehouse", "category": "Storage", "purpose": "Keeps history for queries.", "description": "Column or row store.", "inputs": ["Clean events"], "outputs": ["Query results"], "technologies": ["PostgreSQL"], "dependencies": ["comp-ingest"], "connected_components": ["Metrics engine"]},
            {"id": "comp-metrics", "name": "Metrics engine", "category": "Processing", "purpose": "Aggregates counts, rates, and windows.", "description": "Batch or streaming jobs.", "inputs": ["Warehouse rows"], "outputs": ["Metric series"], "technologies": ["SQL / Python"], "dependencies": ["comp-wh"], "connected_components": ["Anomaly rules", "Analytics dashboard"]},
            {"id": "comp-anom", "name": "Anomaly rules", "category": "Intelligence", "purpose": "Flags series that cross a threshold.", "description": "Rule-based unless a model is trained.", "inputs": ["Metric series"], "outputs": ["Alert candidates"], "technologies": ["Rules"], "dependencies": ["comp-metrics"], "connected_components": ["Analytics dashboard"]},
            {"id": "comp-dash", "name": "Analytics dashboard", "category": "Output", "purpose": "Charts and status for people.", "description": "The visible product.", "inputs": ["Metric series", "Alerts"], "outputs": ["Visual reports"], "technologies": ["Web charts"], "dependencies": ["comp-metrics"], "connected_components": []},
        ],
        "dependencies": ["A durable store", "A charting UI"],
        "logic": "If events arrive, store them, recompute metrics, and if a metric crosses a threshold, show an alert.",
        "workflow": "Sources -> Ingest -> Warehouse -> Metrics -> Dashboard",
        "risks": ["Late events", "Duplicate counts", "Misleading charts"],
        "constraints": ["Every chart must name the aggregation window"],
        "feasibility": {
            "score": 88,
            "technical": "High for a first warehouse + dashboard",
            "software": "SQL warehouse plus a web UI is enough to start",
            "hardware": "Cloud database and app host",
            "data_requirements": "A real event stream or a fixture dataset",
            "complexity": "Moderate; realtime streaming adds complexity",
            "assessment": "A useful V1 is a nightly aggregate plus a few charts. Do not claim ML anomaly accuracy without a model.",
        },
        "build_steps": [
            {"step_number": 1, "title": "Define the event schema", "description": "Name fields and timestamps.", "required_components": ["Event sources", "Ingest API"], "expected_result": "One event type can be posted and rejected if invalid.", "status": "current"},
            {"step_number": 2, "title": "Warehouse tables", "description": "Persist events with indexes on time.", "required_components": ["Event warehouse"], "expected_result": "You can query yesterday's events.", "status": "next"},
            {"step_number": 3, "title": "First metric job", "description": "Daily or hourly counts for one KPI.", "required_components": ["Metrics engine"], "expected_result": "A numeric series you can plot.", "status": "next"},
            {"step_number": 4, "title": "Dashboard charts", "description": "Show that series with labeled axes.", "required_components": ["Analytics dashboard"], "expected_result": "A person understands volume over time without reading SQL.", "status": "next"},
            {"step_number": 5, "title": "Threshold alerts", "description": "Rule-based flags, labeled as such.", "required_components": ["Anomaly rules"], "expected_result": "Crossing a limit lights a status, not a fake accuracy %. ", "status": "next"},
        ],
    }
